6071 - ET - server inactive session timeout
z-open/zerv-core pull request #15
Opened 2020-10-20 21:41 UTC by etelmon

Make sure that when the user closes the browser or all tabs connected via the socket to the zerv server or the network is lost for a duration, the session is invalidated after some time.
The time is based on the inactive session timeout which defines the socket token expiration date and time.

If the user does not re-open  the app before the token expiration, access to zerv (socket/api) will be rejected. User is then supposed to go through the authentication flow.

2020-10-26 22:45 UTC, Jacob-Friesen commented on test/utils.spec.js
> +            expect(utils._setTimeout).toHaveBeenCalledTimes(2);
`zerv-ng-core` review: https://github.com/z-open/zerv-ng-core/pull/18#pullrequestreview-517228915

2020-10-26 23:09 UTC, Jacob-Friesen requested changes
Everything seems fine apart from some failing tests.

2020-10-26 23:09 UTC, Jacob-Friesen commented on package.json
> +    "jsonwebtoken": "8.5.1",
Lodash and eslint should be upgraded too to get rid of some security vulnerabilities.

2020-10-26 23:09 UTC, Jacob-Friesen commented on test/utils.spec.js
> -
` npm run eslint` gives this error:
```
zerv-core/test/cache.service.spec.js
  123:56  error  Missing semicolon  semi
```

2020-10-27 13:49 UTC, etelmon commented on test/utils.spec.js
> -
gulp should not work. it is npm test.

2020-10-27 14:07 UTC, etelmon commented on package.json
> +    "jsonwebtoken": "8.5.1",
Updated lodash for now. eslint is very recent.

2020-10-27 14:07 UTC, etelmon commented on test/utils.spec.js
> -
Fixed lint error.

2020-10-28 21:43 UTC, Jacob-Friesen commented on test/utils.spec.js
> -
It is now good.

2020-10-28 21:43 UTC, Jacob-Friesen approved these changes

2020-10-29 22:56 UTC, merged