6718 - ET -  custom jwt auth implementation
z-open/zerv-core pull request #17
Opened 2021-05-27 13:33 UTC by etelmon

Jira Task: https://zimitio.atlassian.net/browse/ZWEB-6718

Removed dependency to the fork: https://github.com/z-open/socketio-jwt
The code is deprecated and end of life sept 2021

No change to the basic functionality.

Run:
npm test

Performance Considerations
None. It is mainly a refactoring

Sections of the Application Affected
Look up application pr to QA.

2021-05-29 00:04 UTC, Jacob-Friesen requested changes
There are comments about tests and test coverage. Other than those, there are just a bunch of minor issues.

2021-05-29 00:04 UTC, Jacob-Friesen commented on test/transaction.spec.js
> +        /*eslint-disable no-use-before-define*/
This should have after the section of code which it applies to, so further parts in this code still follow this rule.
```
/*eslint-disable no-use-before-define*/
```

2021-05-29 00:04 UTC, Jacob-Friesen commented on lib/authorize/socket-authorize.js
> +module.exports = socketAuthorize;
I cannot find a direct test for this. Since this is merging a deprecated library into our code then us maintaining it, all that functionality should be test. If possible, to 100% code coverage due to how essential this is. You can use the Node.js `nyc` tool to check this: https://github.com/istanbuljs/nyc

2021-06-07 15:24 UTC, etelmon commented on package.json
> +    "xtend": "~2.1.2",
Removed

2021-06-07 15:36 UTC, etelmon commented on package.json
> +    "xtend": "~2.1.2",
Removed

2021-06-07 16:39 UTC, etelmon commented on test/user-session.service.spec.js
> -                    clusterUserSessionId: null,
This issue exists before - due to a test instantiating redis instance for valid purpose. I improved the test .

2021-06-07 16:45 UTC, etelmon commented on test/user-session.service.spec.js
> -                    clusterUserSessionId: null,
I could not reproduce. Are you sure you do not have another process listening to port 9000? pls try again.

2021-06-07 19:36 UTC, etelmon commented on lib/authorize/UnauthorizedError.js
> +UnauthorizedError.prototype.constructor = UnauthorizedError;
This is an old class from socketio-jwt. I re-arranged a bit.

2021-06-07 19:41 UTC, etelmon commented on lib/authorize/http-authorize.js
> + * @param {*} res
Done

2021-06-07 19:43 UTC, etelmon commented on lib/authorize/socket-authorize.js
> + * @param {Function} onConnection
Done

2021-06-07 19:49 UTC, etelmon commented on test/transaction.spec.js
> +        /*eslint-disable no-use-before-define*/
Fixed.

2021-06-07 22:16 UTC, etelmon commented on lib/authorize/socket-authorize.js
> +module.exports = socketAuthorize;
I relied on the old unit tests to create this pr.I rearranged the current unit tests. THere is some good coverage.

2021-06-07 22:24 UTC, etelmon commented on package.json
> +    "xtend": "~2.1.2",
Lib not used. removed.

2021-06-07 22:25 UTC, etelmon commented on package.json
> +    "xtend": "~2.1.2",
Added package-lock

2021-06-08 15:30 UTC, Jacob-Friesen commented on test/user-session.service.spec.js
> -                    clusterUserSessionId: null,
ok that is clearer.

2021-06-08 17:11 UTC, Jacob-Friesen commented on lib/authorize/socket-authorize.js
> +module.exports = socketAuthorize;
Since there was decent test coverage before we will keep as is for now. Though testing still needs to be improved here.

2021-06-08 17:12 UTC, Jacob-Friesen commented on test/user-session.service.spec.js
> -                    clusterUserSessionId: null,
That fixed it. In the README you should add that no process should be running on port 9000 around her "Also check out the unit tests:". Or make the tests error out when port 9000 is occupied.

2021-06-08 17:13 UTC, Jacob-Friesen commented on lib/authorize/http-authorize.js
> + * @param {*} res
`req` and `res` still have empty definitions. Options was just filled in.

2021-06-08 19:38 UTC, etelmon commented on lib/authorize/http-authorize.js
> + * @param {*} res
Done. provided more details.

2021-06-08 19:42 UTC, etelmon commented on test/user-session.service.spec.js
> -                    clusterUserSessionId: null,
Added to the README.

2021-06-10 16:12 UTC, Jacob-Friesen approved these changes

2021-06-10 16:15 UTC, Jacob-Friesen approved these changes
The latest changes look fine now too.

2021-06-10 16:16 UTC, merged