6718 et fix socket buffer
z-open/zerv-core pull request #18
Opened 2021-06-11 20:25 UTC by etelmon

Jira Task: https://zimitio.atlassian.net/browse/ZWEB-6718

This PR fixes an issue preventing large objects to be sent over the socket.

Set the default of the socket http buffer to 100 mgb as it was before with socketio 2.3.0.

Run:
npm test

Performance Considerations
None.

Sections of the Application Affected
Look up application pr to QA.

2021-06-14 21:39 UTC, Jacob-Friesen requested changes
There is just a missing test case issue.

2021-06-14 21:39 UTC, Jacob-Friesen commented on test/zerv-core.spec.js
> +    });
I don't think this case is tested for: `process.env.ZERV_SOCKET_MAX_HTTP_BUFFER_SIZE`

2021-06-15 14:42 UTC, etelmon commented on test/zerv-core.spec.js
> +    });
Variable has no real value at this time. removed.

2021-06-15 15:30 UTC, Jacob-Friesen approved these changes

2021-06-18 02:36 UTC, merged